export const GetAProduct = `query MyQuery ($id:Int){
  products(first: 1, where: {id:$id}) {

    nodes {
      id
      title
      slug
      status
      featuredImage {
        node {
          guid
        }
      }
      seo {
        title
        opengraphTitle
        opengraphSiteName
        opengraphDescription
        metaDesc
        canonical
      }
      productShipping{
        shippingDescription
        shippingImage1{
          node{
            guid
            altText
          }
        }
        shippingImage2{
          node{
            guid
            altText
          }
        }
        shippingImage3{
          node{
            guid
            altText
          }
        }
        shippingImage4{
          node{
            guid
            altText
          }
        }
      }
      productOverview{
        productOverview
      }
      productAddons{
        addOnsFinish
        addOnsFinishImage1{
          node{
            guid
            altText
          }
        }
        addOnsFinishImage2{
          node{
            guid
            altText
          }
        }
        addOnsFinishImage3{
          node{
            guid
            altText
          }
        }
        addOnsFinishImage4{
          node{
            guid
            altText
          }
        }
        addOnsFinishImage5{
          node{
            guid
            altText
          }
        }
      }
      productMaterial{
        materialDescription
        ...productMaterialImages
      }
      productFaqs{
        ...productFaqs
      }
      deliveryInfo{
        deliveryTime
        moq
      }
      gallery{
        productGallery{
          full:fullFileUrl
          meduium:mediumfullFileUrl
          thumb:mediumfullFileUrl
            
        }
      }
      packagingStyles{
        nodes{
          id:databaseId
          name
          slug
          products(first:10){
            nodes{
              id:databaseId
              slug
              title
              featuredImage{
                node{
                  guid
                }
              }
              deliveryInfo{
                deliveryTime
                moq
              }
            }
          }
        }
      }
      industries{
        nodes{
          id:databaseId
          name
          slug
          products(first:10){
            nodes{
              id:databaseId
              slug
              title
              featuredImage{
                node{
                  guid
                }
              }
              deliveryInfo{
                deliveryTime
                moq
              }
            }
          }
        }
      }
      
      productLearnMore{
        learMore:learnMoreAbout
        seactionHeading:otherSeactionHeading
        seactionDetails:otherSeactionDetails
        seactionHeading2:otherSeactionTwoHeading
        seactionDetails2:otherSeactionTwoDetails
      }
    
    }
  }
}

fragment productMaterialImages on ProductMaterial{
  materialImage1{
          node{
            guid
            altText
          }
        }
        materialImage2{
          node{
            guid
            altText
          }
        }
        materialImage3{
          node{
            guid
            altText
          }
        }
        materialImage4{
          node{
            guid
            altText
          }
        }
        materialImage5{
          node{
            guid
            altText
          }
        }
        materialImage6{
          node{
            guid
            altText
          }
        }
}



fragment  productFaqs on ProductFaqs{
        qone
        aone
        qtwo
        atwo
        qthree
        athree
        qfour
        afour
        qfive
        afive
}`